<?xml version="1.0" encoding="utf-8"?>
<style>
  <item>
    <control>MainColor</control>
    <color>-14671840</color>
  </item>
  <item>
    <control>ColorMainText</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>ColorPlayed</control>
    <color>-15921907</color>
  </item>
  <item>
    <control>ColorDisabled</control>
    <color>-14671840</color>
  </item>
  <item>
    <control>waveForm</control>
    <color>-15721923</color>
  </item>
  <item>
    <control>waveBackground</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>MarkerColor</control>
    <color>-65536</color>
  </item>
  <item>
    <control>Music</control>
    <color>-14013910</color>
  </item>
  <item>
    <control>Jingle</control>
    <color>-1379120</color>
  </item>
  <item>
    <control>Sweeper</control>
    <color>-1770776</color>
  </item>
  <item>
    <control>Voiceover</control>
    <color>-1770776</color>
  </item>
  <item>
    <control>Commercial</control>
    <color>-8225</color>
  </item>
  <item>
    <control>InternetStream</control>
    <color>-1249537</color>
  </item>
  <item>
    <control>Other</control>
    <color>-332545</color>
  </item>
  <item>
    <control>VDF</control>
    <color>-1116681</color>
  </item>
  <item>
    <control>Podcast</control>
    <color>-1381646</color>
  </item>
  <item>
    <control>Request</control>
    <color>-1116681</color>
  </item>
  <item>
    <control>News</control>
    <color>-1116681</color>
  </item>
  <item>
    <control>PlaylistEvent</control>
    <color>-8738</color>
  </item>
  <item>
    <control>FileByDate</control>
    <color>-1381646</color>
  </item>
  <item>
    <control>NewestFromFolder</control>
    <color>-1381646</color>
  </item>
  <item>
    <control>Teaser</control>
    <color>-2360355</color>
  </item>
  <item>
    <control>ColorBackLists</control>
    <color>-14869219</color>
  </item>
  <item>
    <control>ColorListText</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>ColorBackListsAlternate</control>
    <color>-14079703</color>
  </item>
  <item>
    <control>ColorListTextAlternate</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>ColorBackListsSelected</control>
    <color>-12500671</color>
  </item>
  <item>
    <control>ColorListTextSelected</control>
    <color>-9455617</color>
  </item>
  <item>
    <control>ColorListBorder</control>
    <color>-15263977</color>
  </item>
  <item>
    <control>ColorListHeaders</control>
    <color>-12237499</color>
  </item>
  <item>
    <control>ColorListHeadersText</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>bColor1</control>
    <color>-11316397</color>
  </item>
  <item>
    <control>bColor2</control>
    <color>-14408668</color>
  </item>
  <item>
    <control>bTextColor</control>
    <color>-1</color>
  </item>
  <item>
    <control>bColor1Over</control>
    <color>-13395457</color>
  </item>
  <item>
    <control>bColor2Over</control>
    <color>-16758420</color>
  </item>
  <item>
    <control>bColor1Selected</control>
    <color>-47546</color>
  </item>
  <item>
    <control>bColor2Selected</control>
    <color>-2818048</color>
  </item>
  <item>
    <control>tColor1</control>
    <color>-11316397</color>
  </item>
  <item>
    <control>tColor2</control>
    <color>-14408668</color>
  </item>
  <item>
    <control>tTextColor</control>
    <color>-1</color>
  </item>
  <item>
    <control>tColor1Over</control>
    <color>-13395457</color>
  </item>
  <item>
    <control>tColor2Over</control>
    <color>-16758420</color>
  </item>
  <item>
    <control>tColor1Selected</control>
    <color>-47546</color>
  </item>
  <item>
    <control>tColor2Selected</control>
    <color>-2818048</color>
  </item>
  <item>
    <control>CounterLabels</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>Intro_CounterColor</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>Outro_CounterColor</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>Remaining_CounterColor</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>Duration_CounterColor</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>ClockColor</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>DateTimeColor</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>SweeperColor</control>
    <color>-1048577</color>
  </item>
  <item>
    <control>VoiceTrackColor</control>
    <color>-1048577</color>
  </item>
  <item>
    <control>TrackSubcategoryColor</control>
    <color>-1048577</color>
  </item>
  <item>
    <control>ArtistColor</control>
    <color>-6960385</color>
  </item>
  <item>
    <control>TitleColor</control>
    <color>-12410625</color>
  </item>
  <item>
    <control>AlbumColor</control>
    <color>-3223858</color>
  </item>
  <item>
    <control>CurrentRotationColor</control>
    <color>-1048577</color>
  </item>
</style>